---
kind: pipeline
type: docker
name: build

steps:
  - name: backend
    image: gradle:jdk11
    commands:
      - gradle build
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
          {{#success build.status}}
            build {{build.number}} succeeded. Good job.
          {{else}}
            build {{build.number}} failed. Fix me please.
          {{/success}}