name: QuantumAPI
version: @version@
main: dev.kscott.quantum.QuantumAPIPlugin
api-version: 1.16
description: A random location generation API for 1.16+
permissions:
  quantum.api.command.rules:
    description: Gives access to /quantum rules.
    default: op
  quantum.api.command.stats:
    description: Gives access to /quantum rules.
    default: op
  quantum.api.command.rulesets:
    description: Gives access to /quantum rulesets.
    default: op
  quantum.api.command.reload:
    description: Gives access to /quantum reload.
    default: op