name: QuantumWild
author: bluely (kadenscott)
version: @version@
main: dev.kscott.quantumwild.QuantumWildPlugin
api-version: 1.16
description: A comprehensive /wild plugin using the Quantum API.
depend:
  - QuantumAPI

softdepend:
  - LuckPerms
  - Essentials

permissions:
  quantum.wild.use:
    default: op
    description: access to /wild
  quantum.wild.world.<world>:
    default: op
    description: allows access to /wild <world> (replace world with whatever world you want to allow access to)
  quantum.wild.others:
    default: op
    description: access to /wild <player> [world]
  quantum.wild.cooldown.bypass:
    default: op
    description: bypasses /wild cooldown
  quantum.wild.warmup.bypass:
    default: op
    description: bypasses /wild warmup