name: QuantumWild
version: @version@
main: dev.kscott.quantumwild.QuantumWildPlugin
api-version: 1.16
description: A comprehensive /wild plugin using the Quantum API.
depend:
  - QuantumAPI

softdepend:
  - LuckPerms
  - Essentials

permissions:
  quantum.wild.use:
    default: op
    description: access to /wild